#pragma once

enum class EEventType
{
	REQUEST_DATA = 1,
	REQUEST_ALL_DATA = 2,
	REQUEST_PROCESS_DATA = 3,
	REQUEST_DISK_DATA = 4,
	ACCEPT_EVENT = 5,
	RESPONSE_DATA = 6,
	SATA_RECEIVED = 7,
	TIMEOUT_EVENT = 8,
	SIGNAL_EVENT = 9,
	CLOSE_EVENT = 10,
};
